package com.backend.nutri_predic.plandia.service;
import com.backend.nutri_predic.common.exception.BusinessException; import com.backend.nutri_predic.common.exception.ResourceNotFoundException; import com.backend.nutri_predic.cliente.repository.ClienteRepository; import com.backend.nutri_predic.ml.client.MetasNutricionalesMlClient; import com.backend.nutri_predic.ml.dto.MlNutritionTargetsRequest; import com.backend.nutri_predic.alimentacion.nutricion.dto.NutrienteDiarioResponse; import com.backend.nutri_predic.alimentacion.nutricion.service.ConsumoNutricionalDiarioService; import com.backend.nutri_predic.plandia.dto.*; import com.backend.nutri_predic.plandia.entity.*; import com.backend.nutri_predic.plandia.repository.*; import com.backend.nutri_predic.prediccionmodelo.entity.PrediccionModelo; import java.math.*; import java.time.LocalDate; import java.util.List; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class PlanDiarioService { private final PlanDiarioRepository planes; private final CumplimientoDiarioRepository cumplimientos; private final ConsumoNutricionalDiarioService consumos; private final ClienteRepository clientes; private final MetasNutricionalesMlClient metasMl;
 public PlanDiarioService(PlanDiarioRepository p,CumplimientoDiarioRepository c,ConsumoNutricionalDiarioService co,ClienteRepository clientes,MetasNutricionalesMlClient metasMl){planes=p;cumplimientos=c;consumos=co;this.clientes=clientes;this.metasMl=metasMl;}
 @Transactional public PlanDiarioResponse generarInicial(Long clienteId,LocalDate fecha){var existente=planes.findByClienteIdAndFechaObjetivo(clienteId,fecha).orElse(null);if(existente!=null&&existente.getEstado()==EstadoPlanDiario.DISPONIBLE)return PlanDiarioResponse.from(existente);var cliente=clientes.findById(clienteId).orElseThrow(()->new ResourceNotFoundException("Cliente"));var objetivo=metasMl.calcular(MlNutritionTargetsRequest.from(cliente));if(!"DISPONIBLE".equals(objetivo.estado())||objetivo.kcal()==null||objetivo.proteinaG()==null||objetivo.carbohidratosG()==null||objetivo.grasasG()==null||objetivo.aguaMl()==null)throw new BusinessException("No se pudieron generar las metas iniciales: "+(objetivo.motivo()==null?"perfil incompleto":objetivo.motivo()));var x=existente==null?new PlanDiario():existente;x.setCliente(cliente);x.setPrediccionModeloOrigen(null);x.setFechaObjetivo(fecha);x.setEstado(EstadoPlanDiario.DISPONIBLE);x.setMotivoNoDisponible(null);x.setFuenteReferencia(objetivo.fuenteFormulaNutricional());x.setVersionReferencia(objetivo.formulaNutricionalVersion());meta(x,objetivo.kcal(),0);meta(x,objetivo.proteinaG(),1);meta(x,objetivo.carbohidratosG(),2);meta(x,objetivo.grasasG(),3);x.setAguaMinMl(objetivo.aguaMl());x.setAguaMaxMl(objetivo.aguaMl());return PlanDiarioResponse.from(planes.save(x));}
 @Transactional public PlanDiario generarOReutilizar(PrediccionModelo prediccion){var fecha=prediccion.getFechaCorte();var plan=planes.findByClienteIdAndFechaObjetivo(prediccion.getCliente().getId(),fecha).map(x->esDePrediccion(x,prediccion)?x:actualizarDesdePrediccion(x,prediccion)).orElseGet(()->crear(prediccion,fecha));recalcularSiExiste(prediccion.getCliente().getId(),fecha);return plan;}
 private PlanDiario crear(PrediccionModelo p,LocalDate fecha){var x=new PlanDiario();x.setCliente(p.getCliente());x.setFechaObjetivo(fecha);return guardarMetasPredictivas(x,p);}
 private boolean esDePrediccion(PlanDiario x,PrediccionModelo p){return x.getPrediccionModeloOrigen()!=null&&x.getPrediccionModeloOrigen().getId().equals(p.getId())&&x.getEstado()==EstadoPlanDiario.DISPONIBLE;}
 private PlanDiario actualizarDesdePrediccion(PlanDiario x,PrediccionModelo p){return guardarMetasPredictivas(x,p);}
 private PlanDiario guardarMetasPredictivas(PlanDiario x,PrediccionModelo p){x.setPrediccionModeloOrigen(p);x.setFuenteReferencia(p.getFuenteFormulaNutricional());x.setVersionReferencia(p.getFormulaNutricionalVersion());if(p.getMetaKcal()==null||p.getMetaProteinaG()==null||p.getMetaCarbohidratosG()==null||p.getMetaGrasasG()==null||p.getMetaAguaMl()==null){x.setEstado(EstadoPlanDiario.NO_DISPONIBLE);x.setMotivoNoDisponible("La predicción no devolvió todas las metas nutricionales");return planes.save(x);}x.setEstado(EstadoPlanDiario.DISPONIBLE);x.setMotivoNoDisponible(null);meta(x,p.getMetaKcal(),0);meta(x,p.getMetaProteinaG(),1);meta(x,p.getMetaCarbohidratosG(),2);meta(x,p.getMetaGrasasG(),3);x.setAguaMinMl(p.getMetaAguaMl());x.setAguaMaxMl(p.getMetaAguaMl());return planes.save(x);}
 private void meta(PlanDiario x,BigDecimal v,int n){if(n==0){x.setEnergiaMinKcal(v);x.setEnergiaMaxKcal(v);}if(n==1){x.setProteinaMinG(v);x.setProteinaMaxG(v);}if(n==2){x.setCarbohidratosMinG(v);x.setCarbohidratosMaxG(v);}if(n==3){x.setGrasasMinG(v);x.setGrasasMaxG(v);}}
 @Transactional public CumplimientoDiario recalcularSiExiste(Long clienteId,LocalDate fecha){var p=planes.findByClienteIdAndFechaObjetivo(clienteId,fecha).orElse(null);if(p==null)return null;var c=cumplimientos.findByPlanId(p.getId()).orElseGet(()->{var x=new CumplimientoDiario();x.setPlan(p);return x;});var real=consumos.obtener(clienteId,fecha);var energia=comparar(p.getEnergiaMinKcal(),p.getEnergiaMaxKcal(),real.kcal());var proteina=comparar(p.getProteinaMinG(),p.getProteinaMaxG(),real.proteinaG());var carbohidratos=comparar(p.getCarbohidratosMinG(),p.getCarbohidratosMaxG(),real.carbohidratosG());var grasas=comparar(p.getGrasasMinG(),p.getGrasasMaxG(),real.grasasG());c.setEnergia(energia.estado(),energia.consumido(),energia.diferencia(),energia.porcentaje());c.setProteina(proteina.estado(),proteina.consumido(),proteina.diferencia(),proteina.porcentaje());c.setCarbohidratos(carbohidratos.estado(),carbohidratos.consumido(),carbohidratos.diferencia(),carbohidratos.porcentaje());c.setGrasas(grasas.estado(),grasas.consumido(),grasas.diferencia(),grasas.porcentaje());return cumplimientos.save(c);}
 private Valor comparar(BigDecimal min,BigDecimal max,NutrienteDiarioResponse real){if(min==null||max==null||real==null||!real.calculable()||real.valor()==null)return new Valor(EstadoCumplimientoComponente.NO_CALCULABLE,null,null,null);var v=real.valor();if(v.compareTo(min)<0)return new Valor(EstadoCumplimientoComponente.POR_DEBAJO,v,v.subtract(min),por(v,min,max));if(v.compareTo(max)>0)return new Valor(EstadoCumplimientoComponente.POR_ENCIMA,v,v.subtract(max),por(v,min,max));return new Valor(EstadoCumplimientoComponente.CUMPLIDA,v,BigDecimal.ZERO,por(v,min,max));}
 private BigDecimal por(BigDecimal v,BigDecimal min,BigDecimal max){return min.compareTo(max)==0&&min.signum()>0?v.multiply(BigDecimal.valueOf(100)).divide(min,2,RoundingMode.HALF_UP):null;} private record Valor(EstadoCumplimientoComponente estado,BigDecimal consumido,BigDecimal diferencia,BigDecimal porcentaje){}
 @Transactional(readOnly=true) public PlanDiarioResponse plan(Long clienteId,LocalDate fecha){return planes.findByClienteIdAndFechaObjetivo(clienteId,fecha).map(PlanDiarioResponse::from).orElse(null);} @Transactional(readOnly=true) public CumplimientoDiarioResponse cumplimiento(Long clienteId,LocalDate fecha){var p=planes.findByClienteIdAndFechaObjetivo(clienteId,fecha).orElse(null);if(p==null)return null;return cumplimientos.findByPlanId(p.getId()).map(CumplimientoDiarioResponse::from).orElse(null);}
 @Transactional(readOnly=true) public List<PlanDiarioResponse> historialPlanes(Long clienteId,LocalDate desde,LocalDate hasta){validarRango(desde,hasta);return planes.findByClienteIdAndFechaObjetivoBetweenOrderByFechaObjetivoAsc(clienteId,desde,hasta).stream().map(PlanDiarioResponse::from).toList();}
 @Transactional(readOnly=true) public List<CumplimientoDiarioResponse> historialCumplimientos(Long clienteId,LocalDate desde,LocalDate hasta){validarRango(desde,hasta);return cumplimientos.findByPlanClienteIdAndPlanFechaObjetivoBetweenOrderByPlanFechaObjetivoAsc(clienteId,desde,hasta).stream().map(CumplimientoDiarioResponse::from).toList();}
 private void validarRango(LocalDate desde,LocalDate hasta){if(desde.isAfter(hasta))throw new BusinessException("desde no puede ser posterior a hasta");}
}
