package com.backend.nutri_predic;

import static org.junit.jupiter.api.Assertions.assertEquals;
import java.sql.DriverManager;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;

class CatalogoUsdaMigrationTests {
    @Test void cargaDoceReferenciasSinDuplicarNiSobrescribir() throws Exception {
        try (var connection = DriverManager.getConnection("jdbc:h2:mem:catalogo-usda;MODE=PostgreSQL;DB_CLOSE_DELAY=-1")) {
            var statement = connection.createStatement();
            statement.execute("CREATE TABLE unidades_medida (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo VARCHAR UNIQUE, nombre VARCHAR, activa BOOLEAN)");
            statement.execute("CREATE TABLE alimentos_catalogo (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre VARCHAR UNIQUE, categoria VARCHAR, unidad_base_id BIGINT, activo BOOLEAN)");
            statement.execute("CREATE TABLE composiciones_nutricionales_alimentos (alimento_catalogo_id BIGINT, version INT, cantidad_referencia NUMERIC, unidad_referencia_id BIGINT, kcal NUMERIC(12,4), proteina_g NUMERIC(12,4), carbohidratos_g NUMERIC(12,4), grasas_g NUMERIC(12,4), fuente_datos VARCHAR(1000), fecha_desde DATE, activo BOOLEAN, creado_en TIMESTAMP WITH TIME ZONE, UNIQUE(alimento_catalogo_id, version))");
            var migration = new ClassPathResource("db/migration/V24__catalogo_alimentos_usda_verificado.sql");
            ScriptUtils.executeSqlScript(connection, migration);
            statement.executeUpdate("UPDATE composiciones_nutricionales_alimentos SET proteina_g = 999 WHERE alimento_catalogo_id = (SELECT id FROM alimentos_catalogo WHERE nombre = 'Quinua cocida (USDA)')");
            ScriptUtils.executeSqlScript(connection, migration);
            try (var result = statement.executeQuery("SELECT COUNT(*) FROM alimentos_catalogo")) { result.next(); assertEquals(12, result.getInt(1)); }
            try (var result = statement.executeQuery("SELECT COUNT(*) FROM composiciones_nutricionales_alimentos WHERE cantidad_referencia = 100")) { result.next(); assertEquals(12, result.getInt(1)); }
            try (var result = statement.executeQuery("SELECT proteina_g FROM composiciones_nutricionales_alimentos WHERE alimento_catalogo_id = (SELECT id FROM alimentos_catalogo WHERE nombre = 'Quinua cocida (USDA)')")) { result.next(); assertEquals(999, result.getBigDecimal(1).intValue()); }
        }
    }
}
