ALTER TABLE IF EXISTS clientes
    ADD COLUMN IF NOT EXISTS peso_kg NUMERIC(5, 2);

ALTER TABLE IF EXISTS clientes
    ADD COLUMN IF NOT EXISTS altura_cm NUMERIC(5, 2);

ALTER TABLE IF EXISTS clientes
    ADD COLUMN IF NOT EXISTS objetivo_fisico VARCHAR(120);
