CREATE TABLE evaluaciones_gpaq (
    evaluacion_actividad_id BIGINT PRIMARY KEY REFERENCES evaluaciones_actividad_fisica(id),
    idioma_version VARCHAR(20) NOT NULL,
    periodo_referencia VARCHAR(40) NOT NULL,
    algoritmo_puntuacion_version VARCHAR(100) NOT NULL,
    trabajo_vigoroso BOOLEAN,
    trabajo_vigoroso_dias INTEGER,
    trabajo_vigoroso_minutos_dia INTEGER,
    trabajo_moderado BOOLEAN,
    trabajo_moderado_dias INTEGER,
    trabajo_moderado_minutos_dia INTEGER,
    transporte_activo BOOLEAN,
    transporte_activo_dias INTEGER,
    transporte_activo_minutos_dia INTEGER,
    recreacion_vigorosa BOOLEAN,
    recreacion_vigorosa_dias INTEGER,
    recreacion_vigorosa_minutos_dia INTEGER,
    recreacion_moderada BOOLEAN,
    recreacion_moderada_dias INTEGER,
    recreacion_moderada_minutos_dia INTEGER,
    tiempo_sentado_minutos_dia INTEGER,
    met_min_semana_trabajo NUMERIC(14,2),
    met_min_semana_transporte NUMERIC(14,2),
    met_min_semana_recreacion NUMERIC(14,2),
    met_min_semana_total NUMERIC(14,2),
    resultado_instrumento VARCHAR(40) NOT NULL,
    estado_calidad VARCHAR(40) NOT NULL
);
