package com.backend.nutri_predic.perfilhabitos.entity;

public enum CodigoDimensionPerfilHabitos {
    ADECUACION_NUTRICIONAL,
    CALIDAD_PATRON_ALIMENTARIO,
    CONSUMO_AGUA,
    PATRON_SUPLEMENTACION,
    CONSUMO_REAL_SUPLEMENTOS_V6,
    ORGANIZACION_ALIMENTARIA,
    ALIMENTACION_REGISTRADA,
    HIDRATACION,
    SUPLEMENTACION_HABITUAL,
    CONSUMO_REAL_SUPLEMENTOS
}
