package com.backend.nutri_predic.plandia.entity;
import jakarta.persistence.*; import java.math.BigDecimal;
@Entity @Table(name="cumplimientos_diarios", uniqueConstraints=@UniqueConstraint(columnNames="plan_diario_id")) public class CumplimientoDiario {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @OneToOne(optional=false) @JoinColumn(name="plan_diario_id") private PlanDiario plan;
 @Enumerated(EnumType.STRING) private EstadoCumplimientoComponente energiaEstado,proteinaEstado,carbohidratosEstado,grasasEstado;
 private BigDecimal energiaConsumido,energiaDiferencia,energiaPorcentaje,proteinaConsumido,proteinaDiferencia,proteinaPorcentaje,carbohidratosConsumido,carbohidratosDiferencia,carbohidratosPorcentaje,grasasConsumido,grasasDiferencia,grasasPorcentaje;
 public Long getId(){return id;} public PlanDiario getPlan(){return plan;} public EstadoCumplimientoComponente getEnergiaEstado(){return energiaEstado;} public EstadoCumplimientoComponente getProteinaEstado(){return proteinaEstado;} public EstadoCumplimientoComponente getCarbohidratosEstado(){return carbohidratosEstado;} public EstadoCumplimientoComponente getGrasasEstado(){return grasasEstado;} public BigDecimal getEnergiaConsumido(){return energiaConsumido;} public BigDecimal getEnergiaDiferencia(){return energiaDiferencia;} public BigDecimal getEnergiaPorcentaje(){return energiaPorcentaje;} public BigDecimal getProteinaConsumido(){return proteinaConsumido;} public BigDecimal getProteinaDiferencia(){return proteinaDiferencia;} public BigDecimal getProteinaPorcentaje(){return proteinaPorcentaje;} public BigDecimal getCarbohidratosConsumido(){return carbohidratosConsumido;} public BigDecimal getCarbohidratosDiferencia(){return carbohidratosDiferencia;} public BigDecimal getCarbohidratosPorcentaje(){return carbohidratosPorcentaje;} public BigDecimal getGrasasConsumido(){return grasasConsumido;} public BigDecimal getGrasasDiferencia(){return grasasDiferencia;} public BigDecimal getGrasasPorcentaje(){return grasasPorcentaje;}
 public void setPlan(PlanDiario v){plan=v;} public void setEnergia(EstadoCumplimientoComponente e,BigDecimal c,BigDecimal d,BigDecimal p){energiaEstado=e;energiaConsumido=c;energiaDiferencia=d;energiaPorcentaje=p;} public void setProteina(EstadoCumplimientoComponente e,BigDecimal c,BigDecimal d,BigDecimal p){proteinaEstado=e;proteinaConsumido=c;proteinaDiferencia=d;proteinaPorcentaje=p;} public void setCarbohidratos(EstadoCumplimientoComponente e,BigDecimal c,BigDecimal d,BigDecimal p){carbohidratosEstado=e;carbohidratosConsumido=c;carbohidratosDiferencia=d;carbohidratosPorcentaje=p;} public void setGrasas(EstadoCumplimientoComponente e,BigDecimal c,BigDecimal d,BigDecimal p){grasasEstado=e;grasasConsumido=c;grasasDiferencia=d;grasasPorcentaje=p;}
}
