package com.backend.nutri_predic.requerimientonutricional.entity;
import com.backend.nutri_predic.common.enums.ObjetivoEnergetico;
import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;
@Entity @Table(name="reglas_requerimiento_nutricional")
public class RequerimientoNutricionalRegla {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;
 @Enumerated(EnumType.STRING) private EstadoReglaRequerimientoNutricional estado;
 private Boolean validada; @Column(name="fuente_referencia") private String fuenteReferencia; @Column(name="version_referencia") private String versionReferencia; private LocalDate vigenteDesde,vigenteHasta;
 private Integer edadMinima,edadMaxima; private BigDecimal pesoMinimoKg,pesoMaximoKg,alturaMinimaCm,alturaMaximaCm; private Boolean realizaActividadFisica; private Integer diasEntrenamientoMinimo,diasEntrenamientoMaximo,duracionSesionMinima,duracionSesionMaxima; private String tipoActividadFisica;
 @Enumerated(EnumType.STRING) private ObjetivoEnergetico objetivoEnergetico;
 @Enumerated(EnumType.STRING) private TipoReglaRequerimientoNutricional tipoRegla;
 @Enumerated(EnumType.STRING) private NutrienteRequerimiento nutriente;
  private BigDecimal kcalObjetivo; @Column(name="proteina_objetivo_g") private BigDecimal proteinaObjetivoG; @Column(name="carbohidratos_objetivo_g") private BigDecimal carbohidratosObjetivoG; @Column(name="grasas_objetivo_g") private BigDecimal grasasObjetivoG;
 private String codigoFormula; private BigDecimal coeficienteBase,coeficienteEdad,coeficientePesoKg,coeficienteAlturaCm,factorActividad,porcentajeMinimoEnergia,porcentajeMaximoEnergia,gramosKgMinimo,gramosKgMaximo;
 public Long getId(){return id;} public EstadoReglaRequerimientoNutricional getEstado(){return estado;} public Boolean getValidada(){return validada;} public String getFuenteReferencia(){return fuenteReferencia;} public String getVersionReferencia(){return versionReferencia;} public LocalDate getVigenteDesde(){return vigenteDesde;} public LocalDate getVigenteHasta(){return vigenteHasta;} public Integer getEdadMinima(){return edadMinima;} public Integer getEdadMaxima(){return edadMaxima;} public BigDecimal getPesoMinimoKg(){return pesoMinimoKg;} public BigDecimal getPesoMaximoKg(){return pesoMaximoKg;} public BigDecimal getAlturaMinimaCm(){return alturaMinimaCm;} public BigDecimal getAlturaMaximaCm(){return alturaMaximaCm;} public Boolean getRealizaActividadFisica(){return realizaActividadFisica;} public Integer getDiasEntrenamientoMinimo(){return diasEntrenamientoMinimo;} public Integer getDiasEntrenamientoMaximo(){return diasEntrenamientoMaximo;} public String getTipoActividadFisica(){return tipoActividadFisica;} public Integer getDuracionSesionMinima(){return duracionSesionMinima;} public Integer getDuracionSesionMaxima(){return duracionSesionMaxima;} public ObjetivoEnergetico getObjetivoEnergetico(){return objetivoEnergetico;} public BigDecimal getKcalObjetivo(){return kcalObjetivo;} public BigDecimal getProteinaObjetivoG(){return proteinaObjetivoG;} public BigDecimal getCarbohidratosObjetivoG(){return carbohidratosObjetivoG;} public BigDecimal getGrasasObjetivoG(){return grasasObjetivoG;} public TipoReglaRequerimientoNutricional getTipoRegla(){return tipoRegla;} public NutrienteRequerimiento getNutriente(){return nutriente;} public String getCodigoFormula(){return codigoFormula;} public BigDecimal getCoeficienteBase(){return coeficienteBase;} public BigDecimal getCoeficienteEdad(){return coeficienteEdad;} public BigDecimal getCoeficientePesoKg(){return coeficientePesoKg;} public BigDecimal getCoeficienteAlturaCm(){return coeficienteAlturaCm;} public BigDecimal getFactorActividad(){return factorActividad;} public BigDecimal getPorcentajeMinimoEnergia(){return porcentajeMinimoEnergia;} public BigDecimal getPorcentajeMaximoEnergia(){return porcentajeMaximoEnergia;} public BigDecimal getGramosKgMinimo(){return gramosKgMinimo;} public BigDecimal getGramosKgMaximo(){return gramosKgMaximo;}
 public void setEstado(EstadoReglaRequerimientoNutricional x){estado=x;} public void setValidada(Boolean x){validada=x;} public void setFuenteReferencia(String x){fuenteReferencia=x;} public void setVersionReferencia(String x){versionReferencia=x;} public void setVigenteDesde(LocalDate x){vigenteDesde=x;} public void setVigenteHasta(LocalDate x){vigenteHasta=x;} public void setEdadMinima(Integer x){edadMinima=x;} public void setEdadMaxima(Integer x){edadMaxima=x;} public void setPesoMinimoKg(BigDecimal x){pesoMinimoKg=x;} public void setPesoMaximoKg(BigDecimal x){pesoMaximoKg=x;} public void setAlturaMinimaCm(BigDecimal x){alturaMinimaCm=x;} public void setAlturaMaximaCm(BigDecimal x){alturaMaximaCm=x;} public void setRealizaActividadFisica(Boolean x){realizaActividadFisica=x;} public void setDiasEntrenamientoMinimo(Integer x){diasEntrenamientoMinimo=x;} public void setDiasEntrenamientoMaximo(Integer x){diasEntrenamientoMaximo=x;} public void setTipoActividadFisica(String x){tipoActividadFisica=x;} public void setDuracionSesionMinima(Integer x){duracionSesionMinima=x;} public void setDuracionSesionMaxima(Integer x){duracionSesionMaxima=x;} public void setObjetivoEnergetico(ObjetivoEnergetico x){objetivoEnergetico=x;} public void setKcalObjetivo(BigDecimal x){kcalObjetivo=x;} public void setProteinaObjetivoG(BigDecimal x){proteinaObjetivoG=x;} public void setCarbohidratosObjetivoG(BigDecimal x){carbohidratosObjetivoG=x;} public void setGrasasObjetivoG(BigDecimal x){grasasObjetivoG=x;} public void setTipoRegla(TipoReglaRequerimientoNutricional x){tipoRegla=x;} public void setNutriente(NutrienteRequerimiento x){nutriente=x;} public void setCodigoFormula(String x){codigoFormula=x;} public void setCoeficienteBase(BigDecimal x){coeficienteBase=x;} public void setCoeficienteEdad(BigDecimal x){coeficienteEdad=x;} public void setCoeficientePesoKg(BigDecimal x){coeficientePesoKg=x;} public void setCoeficienteAlturaCm(BigDecimal x){coeficienteAlturaCm=x;} public void setFactorActividad(BigDecimal x){factorActividad=x;} public void setPorcentajeMinimoEnergia(BigDecimal x){porcentajeMinimoEnergia=x;} public void setPorcentajeMaximoEnergia(BigDecimal x){porcentajeMaximoEnergia=x;} public void setGramosKgMinimo(BigDecimal x){gramosKgMinimo=x;} public void setGramosKgMaximo(BigDecimal x){gramosKgMaximo=x;}
}
