-- Baseline limpio NutriPredict — V1 núcleo.
-- Cubre: unidades_medida, usuarios, clientes, historial_perfiles_cliente,
-- estudios, participaciones_estudio. Sin dependencias externas.

CREATE TABLE unidades_medida (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    activa BOOLEAN NOT NULL
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    rol VARCHAR(255) NOT NULL
        CONSTRAINT chk_usuarios_rol CHECK (rol IN ('CLIENTE', 'ADMIN')),
    activo BOOLEAN NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    actualizado_en TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE REFERENCES usuarios (id),
    edad INTEGER NULL,
    sexo VARCHAR(15) NULL
        CONSTRAINT chk_clientes_sexo CHECK (sexo IN ('FEMENINO', 'MASCULINO')),
    peso_kg NUMERIC(5, 2) NULL,
    altura_cm NUMERIC(5, 2) NULL,
    objetivo_fisico VARCHAR(120) NULL,
    tipo_objetivo_fisico VARCHAR(40) NULL
        CONSTRAINT chk_clientes_tipo_objetivo CHECK (tipo_objetivo_fisico IN (
            'MANTENER_PESO', 'PERDER_PESO', 'GANAR_PESO', 'GANAR_MASA_MUSCULAR',
            'MEJORAR_RENDIMIENTO', 'RECOMPOSICION_CORPORAL', 'OTRO')),
    realiza_actividad_fisica BOOLEAN NULL,
    dias_entrenamiento_semana INTEGER NULL
        CONSTRAINT chk_clientes_dias CHECK (dias_entrenamiento_semana BETWEEN 1 AND 7),
    tipo_actividad_fisica VARCHAR(120) NULL,
    tipo_entrenamiento VARCHAR(30) NULL
        CONSTRAINT chk_clientes_tipo_ent CHECK (tipo_entrenamiento IN (
            'FUERZA', 'CARDIO', 'MIXTO', 'OTRO')),
    duracion_promedio_sesion_minutos INTEGER NULL,
    objetivo_energetico VARCHAR(20) NULL
        CONSTRAINT chk_clientes_obj_energetico CHECK (objetivo_energetico IN (
            'DEFICIT', 'MANTENIMIENTO', 'SUPERAVIT')),
    estado VARCHAR(255) NULL
        CONSTRAINT chk_clientes_estado CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    dataset_group_id UUID NOT NULL UNIQUE,
    creado_en TIMESTAMP WITH TIME ZONE NULL,
    actualizado_en TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE historial_perfiles_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    edad INTEGER NULL,
    sexo VARCHAR(255) NULL,
    peso_kg NUMERIC(5, 2) NULL,
    altura_cm NUMERIC(5, 2) NULL,
    objetivo_fisico VARCHAR(255) NULL,
    tipo_objetivo_fisico VARCHAR(40) NULL,
    realiza_actividad_fisica BOOLEAN NULL,
    dias_entrenamiento_semana INTEGER NULL,
    tipo_actividad_fisica VARCHAR(120) NULL,
    tipo_entrenamiento VARCHAR(30) NULL,
    duracion_promedio_sesion_minutos INTEGER NULL,
    objetivo_energetico VARCHAR(255) NULL,
    fecha_desde DATE NOT NULL,
    vigente_hasta DATE NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_historial_perfil_cliente
    ON historial_perfiles_cliente (cliente_id, fecha_desde);

CREATE TABLE estudios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL
        CONSTRAINT chk_estudios_estado CHECK (estado IN ('BORRADOR', 'ACTIVO', 'INACTIVO')),
    fecha_inicio DATE NULL,
    fecha_fin DATE NULL,
    descripcion VARCHAR(2000) NULL
);

CREATE TABLE participaciones_estudio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudio_id BIGINT NOT NULL REFERENCES estudios (id),
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    codigo_participante VARCHAR(255) NOT NULL,
    grupo VARCHAR(255) NOT NULL
        CONSTRAINT chk_particip_grupo CHECK (grupo IN ('CONTROL', 'EXPERIMENTAL')),
    fecha_asignacion DATE NULL,
    estado VARCHAR(255) NOT NULL
        CONSTRAINT chk_particip_estado CHECK (estado IN ('BORRADOR', 'ACTIVO', 'INACTIVO')),
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_participacion UNIQUE (estudio_id, cliente_id)
);
CREATE INDEX idx_particip_cliente ON participaciones_estudio (cliente_id);
