ALTER TABLE predicciones_modelo DROP CONSTRAINT IF EXISTS chk_pred_momento;
ALTER TABLE predicciones_modelo ADD CONSTRAINT chk_pred_momento
    CHECK (momento_evaluacion IN ('BASAL', 'FINAL', 'DIARIO', 'NO_DETERMINADO'));

ALTER TABLE eventos_analisis DROP CONSTRAINT IF EXISTS chk_evento_momento;
ALTER TABLE eventos_analisis ADD CONSTRAINT chk_evento_momento
    CHECK (momento IN ('BASAL', 'FINAL', 'DIARIO', 'NO_DETERMINADO'));

ALTER TABLE resultados_tests DROP CONSTRAINT IF EXISTS chk_resultado_momento;
ALTER TABLE resultados_tests ADD CONSTRAINT chk_resultado_momento
    CHECK (momento IN ('BASAL', 'FINAL', 'DIARIO', 'NO_DETERMINADO'));

CREATE UNIQUE INDEX uq_prediccion_diaria_exitosa
    ON predicciones_modelo (cliente_id, fecha_corte, model_version)
    WHERE momento_evaluacion = 'DIARIO' AND estado = 'EXITOSA';

CREATE TABLE registros_peso_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    fecha_medicion DATE NOT NULL,
    peso_kg NUMERIC(5, 2) NOT NULL CHECK (peso_kg BETWEEN 1 AND 500),
    peso_anterior_kg NUMERIC(5, 2) NULL,
    variacion_kg NUMERIC(6, 2) NULL,
    variacion_porcentual NUMERIC(8, 2) NULL,
    cambio_anomalo_confirmado BOOLEAN NOT NULL DEFAULT FALSE,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    actualizado_en TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT uq_peso_cliente_fecha UNIQUE (cliente_id, fecha_medicion)
);
CREATE INDEX idx_peso_cliente_fecha ON registros_peso_cliente (cliente_id, fecha_medicion DESC);

CREATE TABLE adaptaciones_diarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    prediccion_modelo_id BIGINT NOT NULL UNIQUE REFERENCES predicciones_modelo (id),
    plan_diario_id BIGINT NULL REFERENCES planes_diarios (id),
    fecha_evaluada DATE NOT NULL,
    fecha_aplicacion DATE NOT NULL,
    contenido_json TEXT NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_adaptacion_cliente_fecha UNIQUE (cliente_id, fecha_aplicacion)
);
CREATE INDEX idx_adaptacion_cliente_fecha
    ON adaptaciones_diarias (cliente_id, fecha_aplicacion DESC);
