-- Baseline limpio NutriPredict — V2 alimentación.
-- Encabezado diario (registros_habitos) + catálogo + líneas de consumo + plantillas.
-- Depende de V1 (clientes, unidades_medida).

CREATE TABLE registros_habitos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    fecha DATE NOT NULL,
    cantidad_comidas INTEGER NULL,
    consumo_agua DOUBLE PRECISION NULL,
    proteinas DOUBLE PRECISION NULL,
    tipo_alimentacion VARCHAR(255) NULL,
    nivel_organizacion VARCHAR(255) NULL,
    desayuno BOOLEAN NULL,
    snacks BOOLEAN NULL,
    alimentos VARCHAR(2000) NULL,
    comidas_cocinadas INTEGER NULL,
    restricciones VARCHAR(1000) NULL,
    consume_suplementos BOOLEAN NULL,
    CONSTRAINT uq_registro_habito UNIQUE (cliente_id, fecha)
);

CREATE TABLE alimentos_catalogo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    categoria VARCHAR(255) NOT NULL,
    unidad_base_id BIGINT NULL REFERENCES unidades_medida (id),
    activo BOOLEAN NOT NULL
);

CREATE TABLE composiciones_nutricionales_alimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alimento_catalogo_id BIGINT NOT NULL REFERENCES alimentos_catalogo (id),
    version INTEGER NOT NULL,
    cantidad_referencia NUMERIC(12, 4) NOT NULL,
    unidad_referencia_id BIGINT NOT NULL REFERENCES unidades_medida (id),
    kcal NUMERIC(12, 4) NULL,
    proteina_g NUMERIC(12, 4) NULL,
    carbohidratos_g NUMERIC(12, 4) NULL,
    grasas_g NUMERIC(12, 4) NULL,
    fibra_g NUMERIC(12, 4) NULL,
    azucar_g NUMERIC(12, 4) NULL,
    sodio_mg NUMERIC(12, 4) NULL,
    fuente_datos VARCHAR(1000) NULL,
    fecha_desde DATE NOT NULL,
    fecha_hasta DATE NULL,
    activo BOOLEAN NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_composicion_alimento UNIQUE (alimento_catalogo_id, version)
);
CREATE INDEX idx_composicion_alimento ON composiciones_nutricionales_alimentos (alimento_catalogo_id);

CREATE TABLE equivalencias_unidades_alimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alimento_catalogo_id BIGINT NOT NULL REFERENCES alimentos_catalogo (id),
    version INTEGER NOT NULL,
    cantidad_origen NUMERIC(12, 4) NOT NULL,
    unidad_origen_id BIGINT NOT NULL REFERENCES unidades_medida (id),
    cantidad_destino NUMERIC(12, 4) NOT NULL,
    unidad_destino_id BIGINT NOT NULL REFERENCES unidades_medida (id),
    fuente_datos VARCHAR(255) NULL,
    fecha_desde DATE NOT NULL,
    fecha_hasta DATE NULL,
    activo BOOLEAN NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_equivalencia_alimento UNIQUE (alimento_catalogo_id, version)
);

CREATE TABLE registros_alimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_habito_id BIGINT NOT NULL REFERENCES registros_habitos (id),
    alimento_id BIGINT NOT NULL REFERENCES alimentos_catalogo (id),
    composicion_nutricional_id BIGINT NULL REFERENCES composiciones_nutricionales_alimentos (id),
    equivalencia_unidad_id BIGINT NULL REFERENCES equivalencias_unidades_alimentos (id),
    cantidad NUMERIC(12, 4) NOT NULL,
    unidad_medida_id BIGINT NOT NULL REFERENCES unidades_medida (id),
    momento_comida VARCHAR(255) NOT NULL
        CONSTRAINT chk_registro_alimento_momento CHECK (momento_comida IN (
            'DESAYUNO', 'MEDIA_MANANA', 'ALMUERZO', 'MERIENDA', 'CENA', 'OTRO'))
);
CREATE INDEX idx_registro_alimento_habito ON registros_alimentos (registro_habito_id);
CREATE INDEX idx_registro_alimento_alimento ON registros_alimentos (alimento_id);

CREATE TABLE plantillas_comida (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    nombre VARCHAR(255) NOT NULL,
    momento_comida VARCHAR(255) NOT NULL
        CONSTRAINT chk_plantilla_momento CHECK (momento_comida IN (
            'DESAYUNO', 'MEDIA_MANANA', 'ALMUERZO', 'MERIENDA', 'CENA', 'OTRO')),
    activa BOOLEAN NOT NULL
);
CREATE INDEX idx_plantilla_cliente ON plantillas_comida (cliente_id);

CREATE TABLE plantillas_comida_detalles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plantilla_id BIGINT NOT NULL REFERENCES plantillas_comida (id),
    alimento_id BIGINT NOT NULL REFERENCES alimentos_catalogo (id),
    cantidad NUMERIC(12, 4) NOT NULL,
    unidad_id BIGINT NOT NULL REFERENCES unidades_medida (id)
);
CREATE INDEX idx_plantilla_detalle ON plantillas_comida_detalles (plantilla_id);
