-- Baseline limpio NutriPredict — V3 suplementación.
-- Catálogo, habitual del cliente (+historial), composición, ingredientes,
-- equivalencias y consumo real diario.
-- Depende de V1 (clientes, unidades_medida) y V2 (registros_habitos).

CREATE TABLE suplementos_catalogo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    tipo VARCHAR(255) NULL,
    marca VARCHAR(255) NULL,
    presentacion VARCHAR(255) NULL,
    unidad_presentacion_id BIGINT NULL REFERENCES unidades_medida (id),
    activo BOOLEAN NULL,
    descripcion VARCHAR(2000) NULL,
    beneficios VARCHAR(2000) NULL,
    recomendaciones VARCHAR(2000) NULL
);

CREATE TABLE suplementos_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    suplemento_id BIGINT NOT NULL REFERENCES suplementos_catalogo (id),
    cantidad DOUBLE PRECISION NULL,
    unidad VARCHAR(255) NULL,
    frecuencia VARCHAR(255) NULL,
    tiempo_uso VARCHAR(255) NULL,
    cantidad_por_toma NUMERIC(12, 4) NULL,
    unidad_medida_id BIGINT NULL REFERENCES unidades_medida (id),
    tomas_por_periodo INTEGER NULL,
    periodo_frecuencia VARCHAR(255) NULL
        CONSTRAINT chk_supl_cli_periodo CHECK (periodo_frecuencia IN (
            'DIA', 'SEMANA', 'MES', 'OTRO')),
    activo BOOLEAN NULL,
    fecha_inicio DATE NULL,
    fecha_fin DATE NULL,
    CONSTRAINT uq_suplemento_cliente UNIQUE (cliente_id, suplemento_id)
);
CREATE INDEX idx_supl_cli_cliente ON suplementos_cliente (cliente_id);

CREATE TABLE historial_suplementos_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asignacion_id BIGINT NOT NULL REFERENCES suplementos_cliente (id),
    cantidad DOUBLE PRECISION NULL,
    unidad VARCHAR(255) NULL,
    frecuencia VARCHAR(255) NULL,
    tiempo_uso VARCHAR(255) NULL,
    cantidad_por_toma NUMERIC(12, 4) NULL,
    unidad_medida_id BIGINT NULL REFERENCES unidades_medida (id),
    tomas_por_periodo INTEGER NULL,
    periodo_frecuencia VARCHAR(255) NULL,
    activo BOOLEAN NULL,
    fecha_inicio DATE NULL,
    fecha_fin DATE NULL,
    registrado_en TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_hist_supl_asignacion ON historial_suplementos_cliente (asignacion_id);

CREATE TABLE suplementos_ingredientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suplemento_catalogo_id BIGINT NOT NULL REFERENCES suplementos_catalogo (id),
    ingrediente VARCHAR(255) NOT NULL,
    cantidad_por_porcion NUMERIC(12, 4) NOT NULL,
    unidad_medida_id BIGINT NOT NULL REFERENCES unidades_medida (id)
);

CREATE TABLE composiciones_suplementos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suplemento_catalogo_id BIGINT NOT NULL REFERENCES suplementos_catalogo (id),
    version INTEGER NULL,
    cantidad_porcion_referencia NUMERIC(12, 4) NULL,
    energia_kcal_porcion NUMERIC(10, 2) NULL,
    unidad_porcion_id BIGINT NULL REFERENCES unidades_medida (id),
    fecha_desde DATE NULL,
    fecha_hasta DATE NULL,
    activo BOOLEAN NULL,
    fuente_datos VARCHAR(255) NULL
);

CREATE TABLE componentes_composicion_suplementos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    composicion_suplemento_id BIGINT NOT NULL REFERENCES composiciones_suplementos (id),
    tipo VARCHAR(255) NULL
        CONSTRAINT chk_componente_tipo CHECK (tipo IN (
            'PROTEINA', 'CREATINA', 'CAFEINA', 'CARBOHIDRATOS', 'GRASAS', 'SODIO', 'OTRO')),
    nombre_otro VARCHAR(255) NULL,
    cantidad NUMERIC(19, 2) NULL,
    unidad_id BIGINT NULL REFERENCES unidades_medida (id)
);
CREATE INDEX idx_componente_composicion ON componentes_composicion_suplementos (composicion_suplemento_id);

CREATE TABLE equivalencias_unidades_suplementos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suplemento_catalogo_id BIGINT NOT NULL REFERENCES suplementos_catalogo (id),
    version INTEGER NULL,
    cantidad_origen NUMERIC(19, 2) NULL,
    unidad_origen_id BIGINT NULL REFERENCES unidades_medida (id),
    cantidad_destino NUMERIC(19, 2) NULL,
    unidad_destino_id BIGINT NULL REFERENCES unidades_medida (id),
    fecha_desde DATE NULL,
    fecha_hasta DATE NULL,
    activo BOOLEAN NULL
);

CREATE TABLE registros_consumo_suplemento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_habito_id BIGINT NOT NULL REFERENCES registros_habitos (id),
    suplemento_cliente_id BIGINT NOT NULL REFERENCES suplementos_cliente (id),
    cantidad_consumida NUMERIC(12, 4) NOT NULL,
    unidad_medida_id BIGINT NOT NULL REFERENCES unidades_medida (id),
    numero_tomas INTEGER NULL,
    composicion_suplemento_id BIGINT NULL REFERENCES composiciones_suplementos (id),
    equivalencia_unidad_suplemento_id BIGINT NULL REFERENCES equivalencias_unidades_suplementos (id),
    observacion VARCHAR(500) NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_registro_consumo_supl UNIQUE (registro_habito_id, suplemento_cliente_id)
);
CREATE INDEX idx_reg_consumo_habito ON registros_consumo_suplemento (registro_habito_id);
