-- Baseline limpio NutriPredict — V4 predicción.
-- Catálogo de procedimientos, eventos de análisis (TPP), predicciones del
-- modelo y fallos del ciclo post-predicción.
-- Depende de V1 (clientes, usuarios, participaciones_estudio).
-- Va antes que conocimiento/indicadores porque sesiones y evaluaciones
-- referencian predicciones_modelo.

CREATE TABLE procedimientos_analisis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(255) NULL,
    "version" INTEGER NULL,
    tipo VARCHAR(255) NULL
        CONSTRAINT chk_procedimiento_tipo CHECK (tipo IN ('MANUAL', 'SOFTWARE_IA')),
    nombre VARCHAR(255) NULL,
    descripcion_operativa VARCHAR(255) NULL,
    fuente_referencia VARCHAR(255) NULL,
    vigente_desde TIMESTAMP WITH TIME ZONE NULL,
    activo BOOLEAN NOT NULL,
    validado_por VARCHAR(255) NULL,
    validado_en TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT uq_procedimiento UNIQUE (codigo, "version")
);

CREATE TABLE predicciones_modelo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    participacion_estudio_id BIGINT NULL REFERENCES participaciones_estudio (id),
    momento_evaluacion VARCHAR(255) NOT NULL
        CONSTRAINT chk_pred_momento CHECK (momento_evaluacion IN (
            'BASAL', 'FINAL', 'NO_DETERMINADO')),
    fecha_corte DATE NOT NULL,
    clasificacion_predicha VARCHAR(255) NULL
        CONSTRAINT chk_pred_clasif CHECK (clasificacion_predicha IN (
            'ADECUADO', 'MEJORABLE', 'CRITICO')),
    prob_adecuado NUMERIC(8, 6) NULL,
    prob_mejorable NUMERIC(8, 6) NULL,
    prob_critico NUMERIC(8, 6) NULL,
    model_version VARCHAR(255) NULL,
    schema_version VARCHAR(80) NOT NULL,
    fecha_prediccion TIMESTAMP WITH TIME ZONE NOT NULL,
    tiempo_inferencia_ms BIGINT NULL,
    inference_ms NUMERIC(14, 6) NULL,
    inferred_at TIMESTAMP WITH TIME ZONE NULL,
    model_type VARCHAR(80) NULL,
    training_data_type VARCHAR(80) NULL,
    is_thesis_final_model BOOLEAN NULL,
    feature_count INTEGER NULL,
    estado VARCHAR(255) NOT NULL
        CONSTRAINT chk_pred_estado CHECK (estado IN ('EXITOSA', 'FALLIDA')),
    mensaje_error VARCHAR(2000) NULL,
    observaciones_tecnicas VARCHAR(2000) NULL
);
CREATE INDEX idx_pred_modelo_cliente_corte
    ON predicciones_modelo (cliente_id, fecha_corte);

CREATE TABLE eventos_analisis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_evento BIGINT NULL,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    procedimiento_analisis_id BIGINT NULL REFERENCES procedimientos_analisis (id),
    participacion_estudio_id BIGINT NULL REFERENCES participaciones_estudio (id),
    evaluador_usuario_id BIGINT NULL REFERENCES usuarios (id),
    prediccion_modelo_id BIGINT NULL REFERENCES predicciones_modelo (id),
    fecha_corte DATE NULL,
    datos_listos_en TIMESTAMP WITH TIME ZONE NULL,
    analisis_iniciado_en TIMESTAMP WITH TIME ZONE NULL,
    variables_preparadas_en TIMESTAMP WITH TIME ZONE NULL,
    modelo_solicitado_en TIMESTAMP WITH TIME ZONE NULL,
    modelo_respondio_en TIMESTAMP WITH TIME ZONE NULL,
    resultado_disponible_en TIMESTAMP WITH TIME ZONE NULL,
    momento VARCHAR(255) NULL
        CONSTRAINT chk_evento_momento CHECK (momento IN (
            'BASAL', 'FINAL', 'NO_DETERMINADO')),
    estado_validez VARCHAR(255) NULL
        CONSTRAINT chk_evento_validez CHECK (estado_validez IN (
            'VALIDA', 'INVALIDA', 'NO_DETERMINADA')),
    origen_resultado VARCHAR(255) NULL
        CONSTRAINT chk_evento_origen CHECK (origen_resultado IN (
            'GENERADO', 'REUTILIZADO')),
    motivo_invalidez VARCHAR(255) NULL,
    observaciones_tecnicas VARCHAR(255) NULL
);
CREATE INDEX idx_evento_cliente ON eventos_analisis (cliente_id);

CREATE TABLE fallos_ciclo_post_prediccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediccion_modelo_id BIGINT NOT NULL REFERENCES predicciones_modelo (id),
    modulo VARCHAR(30) NOT NULL,
    tipo_error VARCHAR(160) NOT NULL,
    ocurrido_en TIMESTAMP WITH TIME ZONE NOT NULL,
    detalle VARCHAR(1000) NULL
);
