-- Baseline limpio NutriPredict — V5 conocimiento.
-- PCC oficial (instrumentos + evaluaciones) y práctica IA post-modelo.
-- Depende de V1 (clientes, usuarios, participaciones) y V4 (predicciones_modelo).

CREATE TABLE temas_conocimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL
);

CREATE TABLE preguntas_conocimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enunciado VARCHAR(2000) NOT NULL,
    opciona VARCHAR(255) NOT NULL,
    opcionb VARCHAR(255) NOT NULL,
    opcionc VARCHAR(255) NOT NULL,
    opciond VARCHAR(255) NOT NULL,
    respuesta_correcta VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NULL,
    dificultad VARCHAR(255) NULL,
    grupo_version VARCHAR(36) NOT NULL,
    version INTEGER NOT NULL,
    tema VARCHAR(255) NULL,
    tema_id BIGINT NULL REFERENCES temas_conocimiento (id),
    subtema VARCHAR(255) NULL,
    explicacion VARCHAR(2000) NULL,
    fuente_referencia VARCHAR(1000) NULL,
    estado_pregunta VARCHAR(255) NOT NULL
        CONSTRAINT chk_pregunta_estado CHECK (estado_pregunta IN ('ACTIVA', 'INACTIVA')),
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    vigente_desde TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_pregunta_version UNIQUE (grupo_version, version)
);

CREATE TABLE instrumentos_conocimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(255) NOT NULL,
    version INTEGER NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL
        CONSTRAINT chk_instrumento_estado CHECK (estado IN ('BORRADOR', 'ACTIVO', 'INACTIVO')),
    vigente_desde TIMESTAMP WITH TIME ZONE NULL,
    fuente_referencia VARCHAR(1000) NULL,
    metadata_validacion VARCHAR(4000) NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_instrumento UNIQUE (codigo, version)
);

CREATE TABLE instrumentos_preguntas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrumento_id BIGINT NOT NULL REFERENCES instrumentos_conocimiento (id),
    pregunta_id BIGINT NOT NULL REFERENCES preguntas_conocimiento (id),
    orden INTEGER NOT NULL,
    puntuacion NUMERIC(12, 4) NOT NULL,
    CONSTRAINT uq_instrumento_pregunta UNIQUE (instrumento_id, pregunta_id),
    CONSTRAINT uq_instrumento_orden UNIQUE (instrumento_id, orden)
);

CREATE TABLE resultados_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    total_preguntas INTEGER NOT NULL,
    correctas INTEGER NOT NULL,
    porcentaje DOUBLE PRECISION NOT NULL,
    nivel VARCHAR(255) NULL
        CONSTRAINT chk_resultado_nivel CHECK (nivel IN ('BAJO', 'MEDIO', 'ALTO')),
    fecha TIMESTAMP WITH TIME ZONE NULL,
    instrumento_id BIGINT NULL REFERENCES instrumentos_conocimiento (id),
    participacion_estudio_id BIGINT NULL REFERENCES participaciones_estudio (id),
    momento VARCHAR(255) NULL
        CONSTRAINT chk_resultado_momento CHECK (momento IN (
            'BASAL', 'FINAL', 'NO_DETERMINADO')),
    estado_validez VARCHAR(255) NULL
        CONSTRAINT chk_resultado_validez CHECK (estado_validez IN (
            'VALIDA', 'INVALIDA', 'NO_DETERMINADA')),
    motivo_invalidez VARCHAR(255) NULL,
    puntaje_obtenido NUMERIC(19, 2) NULL,
    puntaje_maximo NUMERIC(19, 2) NULL
);
CREATE INDEX idx_resultado_cliente ON resultados_tests (cliente_id);

CREATE TABLE respuestas_test (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resultado_id BIGINT NOT NULL REFERENCES resultados_tests (id),
    pregunta_id BIGINT NOT NULL REFERENCES preguntas_conocimiento (id),
    respuesta VARCHAR(255) NOT NULL,
    correcta BOOLEAN NOT NULL
);
CREATE INDEX idx_respuesta_resultado ON respuestas_test (resultado_id);

CREATE TABLE resultados_tema_test (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resultado_id BIGINT NOT NULL REFERENCES resultados_tests (id),
    tema VARCHAR(255) NOT NULL,
    tema_id BIGINT NULL REFERENCES temas_conocimiento (id),
    correctas INTEGER NOT NULL,
    total INTEGER NOT NULL,
    porcentaje DOUBLE PRECISION NOT NULL,
    puntaje_obtenido NUMERIC(19, 2) NULL,
    puntaje_maximo NUMERIC(19, 2) NULL,
    requiere_refuerzo BOOLEAN NULL,
    criterio_refuerzo_aplicado VARCHAR(255) NULL,
    CONSTRAINT uq_resultado_tema UNIQUE (resultado_id, tema)
);

CREATE TABLE sesiones_conocimiento_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediccion_modelo_id BIGINT NOT NULL REFERENCES predicciones_modelo (id),
    reintento_de_sesion_id BIGINT NULL REFERENCES sesiones_conocimiento_ia (id),
    instrumento_id BIGINT NULL REFERENCES instrumentos_conocimiento (id),
    configuracion_version VARCHAR(255) NOT NULL,
    model_version_predictivo VARCHAR(255) NOT NULL,
    schema_version VARCHAR(255) NOT NULL,
    proveedor_ia VARCHAR(255) NOT NULL,
    modelo_generativo VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL
        CONSTRAINT chk_sesion_estado CHECK (estado IN (
            'GENERADA', 'RESPONDIDA', 'IA_NO_DISPONIBLE')),
    generado_en TIMESTAMP WITH TIME ZONE NULL,
    respondida_en TIMESTAMP WITH TIME ZONE NULL,
    fallido_en TIMESTAMP WITH TIME ZONE NULL,
    codigo_error_tecnico VARCHAR(255) NULL,
    etapa_error VARCHAR(255) NULL,
    tipo_excepcion_seguro VARCHAR(255) NULL,
    http_status_gemini INTEGER NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_sesion_pred_config UNIQUE (prediccion_modelo_id, configuracion_version)
);

CREATE TABLE preguntas_generadas_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesion_id BIGINT NOT NULL REFERENCES sesiones_conocimiento_ia (id),
    tema VARCHAR(255) NOT NULL,
    subtema VARCHAR(255) NULL,
    dificultad VARCHAR(255) NOT NULL,
    enunciado VARCHAR(2000) NOT NULL,
    opcion_a VARCHAR(1000) NOT NULL,
    opcion_b VARCHAR(1000) NOT NULL,
    opcion_c VARCHAR(1000) NOT NULL,
    opcion_d VARCHAR(1000) NOT NULL,
    respuesta_correcta VARCHAR(255) NOT NULL,
    explicacion VARCHAR(2000) NOT NULL,
    orden INTEGER NOT NULL,
    creada_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_pregunta_sesion_orden UNIQUE (sesion_id, orden)
);
CREATE INDEX idx_pregunta_sesion ON preguntas_generadas_ia (sesion_id);

CREATE TABLE respuestas_adaptativas_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesion_id BIGINT NOT NULL REFERENCES sesiones_conocimiento_ia (id),
    pregunta_generada_ia_id BIGINT NOT NULL REFERENCES preguntas_generadas_ia (id),
    opcion_seleccionada VARCHAR(1) NOT NULL,
    correcta BOOLEAN NOT NULL,
    respondida_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_respuesta_sesion_pregunta UNIQUE (sesion_id, pregunta_generada_ia_id)
);

CREATE TABLE trazas_llamadas_gemini (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediccion_modelo_id BIGINT NOT NULL REFERENCES predicciones_modelo (id),
    fecha TIMESTAMP WITH TIME ZONE NOT NULL,
    exito BOOLEAN NOT NULL,
    cantidad_preguntas INTEGER NOT NULL,
    reutilizada BOOLEAN NOT NULL
);
