-- Baseline limpio NutriPredict — V6 indicadores.
-- Actividad/GPAQ, reglas nutricionales, PCS oficial, ground truth Y (NO es PCS)
-- y planes nutricionales.
-- Depende de V1 (clientes, usuarios, participaciones), V3 (suplementos_catalogo),
-- V4 (predicciones_modelo) y V5 (instrumentos: ninguno directo).

-- Actividad física ---------------------------------------------------------
CREATE TABLE evaluaciones_actividad_fisica (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    fecha_evaluacion DATE NOT NULL,
    instrumento_codigo VARCHAR(100) NOT NULL,
    instrumento_version VARCHAR(60) NOT NULL,
    nivel_resultado VARCHAR(100) NOT NULL,
    valor_resultado NUMERIC(19, 2) NULL,
    fuente_referencia VARCHAR(300) NOT NULL,
    validada BOOLEAN NULL,
    vigencia_desde DATE NULL,
    vigencia_hasta DATE NULL
);
CREATE INDEX idx_eval_actividad_cliente ON evaluaciones_actividad_fisica (cliente_id);

CREATE TABLE evaluaciones_gpaq (
    evaluacion_actividad_id BIGINT PRIMARY KEY REFERENCES evaluaciones_actividad_fisica (id),
    idioma_version VARCHAR(20) NOT NULL,
    periodo_referencia VARCHAR(40) NOT NULL,
    algoritmo_puntuacion_version VARCHAR(100) NOT NULL,
    trabajo_vigoroso BOOLEAN NULL,
    trabajo_moderado BOOLEAN NULL,
    transporte_activo BOOLEAN NULL,
    recreacion_vigorosa BOOLEAN NULL,
    recreacion_moderada BOOLEAN NULL,
    trabajo_vigoroso_dias INTEGER NULL,
    trabajo_moderado_dias INTEGER NULL,
    transporte_activo_dias INTEGER NULL,
    recreacion_vigorosa_dias INTEGER NULL,
    recreacion_moderada_dias INTEGER NULL,
    trabajo_vigoroso_minutos_dia INTEGER NULL,
    trabajo_moderado_minutos_dia INTEGER NULL,
    transporte_activo_minutos_dia INTEGER NULL,
    recreacion_vigorosa_minutos_dia INTEGER NULL,
    recreacion_moderada_minutos_dia INTEGER NULL,
    tiempo_sentado_minutos_dia INTEGER NULL,
    met_min_semana_trabajo NUMERIC(19, 2) NULL,
    met_min_semana_transporte NUMERIC(19, 2) NULL,
    met_min_semana_recreacion NUMERIC(19, 2) NULL,
    met_min_semana_total NUMERIC(19, 2) NULL,
    resultado_instrumento VARCHAR(40) NOT NULL
        CONSTRAINT chk_gpaq_resultado CHECK (resultado_instrumento IN (
            'CUMPLE_RECOMENDACION', 'NO_CUMPLE_RECOMENDACION', 'NO_CALCULABLE')),
    estado_calidad VARCHAR(40) NOT NULL
        CONSTRAINT chk_gpaq_calidad CHECK (estado_calidad IN (
            'VALIDA', 'INCOMPLETA', 'INCONSISTENTE'))
);

CREATE TABLE mapeos_categoria_actividad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrumento_codigo VARCHAR(255) NULL,
    instrumento_version VARCHAR(255) NULL,
    resultado_origen VARCHAR(255) NULL,
    categoria_destino VARCHAR(255) NULL,
    fuente_referencia VARCHAR(255) NULL,
    version_referencia VARCHAR(255) NULL,
    validada BOOLEAN NULL,
    vigencia_desde DATE NULL,
    vigencia_hasta DATE NULL
);

-- Reglas nutricionales ------------------------------------------------------
CREATE TABLE reglas_requerimiento_nutricional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado VARCHAR(255) NULL,
    validada BOOLEAN NULL,
    fuente_referencia VARCHAR(255) NULL,
    version_referencia VARCHAR(255) NULL,
    vigente_desde DATE NULL,
    vigente_hasta DATE NULL,
    edad_minima INTEGER NULL,
    edad_maxima INTEGER NULL,
    peso_minimo_kg NUMERIC(19, 2) NULL,
    peso_maximo_kg NUMERIC(19, 2) NULL,
    altura_minima_cm NUMERIC(19, 2) NULL,
    altura_maxima_cm NUMERIC(19, 2) NULL,
    realiza_actividad_fisica BOOLEAN NULL,
    dias_entrenamiento_minimo INTEGER NULL,
    dias_entrenamiento_maximo INTEGER NULL,
    duracion_sesion_minima INTEGER NULL,
    duracion_sesion_maxima INTEGER NULL,
    tipo_actividad_fisica VARCHAR(255) NULL,
    objetivo_energetico VARCHAR(255) NULL,
    tipo_regla VARCHAR(255) NULL,
    nutriente VARCHAR(255) NULL,
    kcal_objetivo NUMERIC(19, 2) NULL,
    proteina_objetivog NUMERIC(19, 2) NULL,
    carbohidratos_objetivog NUMERIC(19, 2) NULL,
    grasas_objetivog NUMERIC(19, 2) NULL,
    codigo_formula VARCHAR(255) NULL,
    coeficiente_base NUMERIC(19, 2) NULL,
    coeficiente_edad NUMERIC(19, 2) NULL,
    coeficiente_peso_kg NUMERIC(19, 2) NULL,
    coeficiente_altura_cm NUMERIC(19, 2) NULL,
    factor_actividad NUMERIC(19, 2) NULL,
    porcentaje_minimo_energia NUMERIC(19, 2) NULL,
    porcentaje_maximo_energia NUMERIC(19, 2) NULL,
    gramos_kg_minimo NUMERIC(19, 2) NULL,
    gramos_kg_maximo NUMERIC(19, 2) NULL
);

CREATE TABLE factores_actividad_regla (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nivel_actividad VARCHAR(30) NOT NULL
        CONSTRAINT chk_factor_nivel CHECK (nivel_actividad IN (
            'SEDENTARIO', 'LIGERA', 'MODERADA', 'INTENSA', 'MUY_INTENSA', 'NO_DETERMINADA')),
    factor NUMERIC(6, 4) NOT NULL,
    fuente_referencia VARCHAR(400) NOT NULL,
    version_referencia VARCHAR(80) NOT NULL,
    vigente_desde DATE NULL,
    vigente_hasta DATE NULL,
    estado VARCHAR(255) NULL,
    validada BOOLEAN NULL,
    CONSTRAINT uq_factor_actividad UNIQUE (nivel_actividad, version_referencia)
);

-- PCS oficial ---------------------------------------------------------------
CREATE TABLE criterios_consumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL,
    version INTEGER NOT NULL,
    estado VARCHAR(30) NOT NULL
        CONSTRAINT chk_rubrica_pcs_estado CHECK (estado IN ('BORRADOR', 'ACTIVO', 'INACTIVO')),
    ventana_dias INTEGER NULL,
    vigente_desde TIMESTAMP WITH TIME ZONE NULL,
    vigente_hasta TIMESTAMP WITH TIME ZONE NULL,
    validada BOOLEAN NOT NULL,
    observacion VARCHAR(2000) NULL,
    fuente_referencia VARCHAR(1000) NULL,
    validado_por VARCHAR(255) NULL,
    validado_en TIMESTAMP WITH TIME ZONE NULL,
    version_evaluador VARCHAR(80) NULL,
    metadata_validacion VARCHAR(4000) NULL,
    regla_global VARCHAR(4000) NULL,
    CONSTRAINT uq_rubrica_pcs UNIQUE (codigo, version)
);

CREATE TABLE reglas_criterio_consumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criterio_id BIGINT NOT NULL REFERENCES criterios_consumo (id),
    alcance VARCHAR(30) NOT NULL,
    suplemento_catalogo_id BIGINT NULL REFERENCES suplementos_catalogo (id),
    componente_tipo VARCHAR(50) NULL,
    elemento_aplicable VARCHAR(255) NULL,
    metrica VARCHAR(100) NULL,
    cantidad_referencia NUMERIC(18, 6) NULL,
    cantidad_referencia_hasta NUMERIC(18, 6) NULL,
    ambito_aporte VARCHAR(30) NULL
        CONSTRAINT chk_criterio_ambito CHECK (ambito_aporte IN (
            'TOTAL_DIETA', 'SOLO_SUPLEMENTOS')),
    unidad_referencia VARCHAR(30) NULL,
    unidad_normalizada VARCHAR(30) NULL,
    frecuencia VARCHAR(80) NULL,
    numero_tomas INTEGER NULL,
    ventana_dias INTEGER NULL,
    requiere_composicion BOOLEAN NOT NULL,
    tipo_evaluador VARCHAR(100) NULL,
    parametros VARCHAR(4000) NULL,
    fuente_referencia_criterio VARCHAR(1000) NULL,
    version_referencia VARCHAR(100) NULL,
    observacion_metodologica VARCHAR(2000) NULL
);
CREATE INDEX idx_criterio_rubrica ON reglas_criterio_consumo (criterio_id);

CREATE TABLE evaluaciones_consumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    participacion_estudio_id BIGINT NULL REFERENCES participaciones_estudio (id),
    prediccion_modelo_id BIGINT NULL REFERENCES predicciones_modelo (id),
    criterio_consumo_id BIGINT NULL REFERENCES criterios_consumo (id),
    fecha_corte DATE NOT NULL,
    fecha_inicio DATE NOT NULL,
    ventana_dias INTEGER NOT NULL,
    momento VARCHAR(255) NOT NULL,
    estado_clasificacion VARCHAR(255) NOT NULL
        CONSTRAINT chk_eval_consumo_clasif CHECK (estado_clasificacion IN (
            'ALTO', 'NO_ALTO', 'NO_DETERMINADA')),
    motivo_clasificacion VARCHAR(100) NULL,
    estado_validez VARCHAR(255) NOT NULL,
    motivo_invalidez VARCHAR(1000) NULL,
    alto_consumo BOOLEAN NULL,
    fecha_evaluacion TIMESTAMP WITH TIME ZONE NOT NULL,
    schema_version VARCHAR(80) NOT NULL,
    advertencias VARCHAR(4000) NULL
);
CREATE INDEX idx_eval_consumo_cliente_corte
    ON evaluaciones_consumo (cliente_id, fecha_corte);

CREATE TABLE detalles_evaluacion_consumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_consumo_id BIGINT NOT NULL REFERENCES evaluaciones_consumo (id),
    criterio_evaluado_id BIGINT NULL,
    componente VARCHAR(100) NULL,
    fuente VARCHAR(30) NULL,
    cantidad_observada NUMERIC(19, 2) NULL,
    referencia_aplicada NUMERIC(19, 2) NULL,
    referencia_aplicada_hasta NUMERIC(19, 2) NULL,
    resultado VARCHAR(30) NULL,
    motivo_no_calculable VARCHAR(1000) NULL
);
CREATE INDEX idx_detalle_evaluacion ON detalles_evaluacion_consumo (evaluacion_consumo_id);

CREATE TABLE snapshots_evaluacion_consumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_consumo_id BIGINT NOT NULL UNIQUE REFERENCES evaluaciones_consumo (id),
    schema_version VARCHAR(255) NULL,
    contenido_json TEXT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NULL
);

-- Ground truth Y (NO es PCS) -------------------------------------------------
CREATE TABLE rubricas_perfil_habitos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL,
    version NUMERIC(5, 2) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(2000) NULL,
    estado VARCHAR(255) NOT NULL
        CONSTRAINT chk_rubrica_gt_estado CHECK (estado IN ('BORRADOR', 'ACTIVA', 'INACTIVA')),
    vigente_desde TIMESTAMP WITH TIME ZONE NULL,
    vigente_hasta TIMESTAMP WITH TIME ZONE NULL,
    validado_por VARCHAR(255) NULL,
    validado_en TIMESTAMP WITH TIME ZONE NULL,
    observacion_validacion VARCHAR(2000) NULL,
    tipo_validacion VARCHAR(80) NULL,
    fuente_validacion VARCHAR(4000) NULL,
    version_fuente VARCHAR(80) NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_rubrica_gt UNIQUE (codigo, version)
);

CREATE TABLE dimensiones_rubrica_perfil_habitos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rubrica_id BIGINT NOT NULL REFERENCES rubricas_perfil_habitos (id),
    codigo VARCHAR(60) NOT NULL
        CONSTRAINT chk_dimension_gt_codigo CHECK (codigo IN (
            'ADECUACION_NUTRICIONAL', 'CALIDAD_PATRON_ALIMENTARIO', 'CONSUMO_AGUA',
            'PATRON_SUPLEMENTACION', 'CONSUMO_REAL_SUPLEMENTOS_V6', 'ORGANIZACION_ALIMENTARIA',
            'ALIMENTACION_REGISTRADA', 'HIDRATACION', 'SUPLEMENTACION_HABITUAL',
            'CONSUMO_REAL_SUPLEMENTOS')),
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(2000) NULL,
    puntaje_minimo NUMERIC(6, 2) NULL,
    puntaje_maximo NUMERIC(6, 2) NULL,
    peso_porcentual NUMERIC(6, 2) NULL,
    orden INTEGER NOT NULL,
    CONSTRAINT uq_dimension_perfil_rubrica_codigo UNIQUE (rubrica_id, codigo),
    CONSTRAINT uq_dimension_perfil_rubrica_orden UNIQUE (rubrica_id, orden)
);

CREATE TABLE criterios_rubrica_perfil_habitos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rubrica_id BIGINT NOT NULL REFERENCES rubricas_perfil_habitos (id),
    dimension_id BIGINT NOT NULL REFERENCES dimensiones_rubrica_perfil_habitos (id),
    codigo VARCHAR(80) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    tipo_evaluacion VARCHAR(40) NOT NULL
        CONSTRAINT chk_criterio_gt_tipo CHECK (tipo_evaluacion IN (
            'AUTOMATICO', 'MANUAL_ESPECIALISTA', 'DESCRIPTIVO')),
    componente VARCHAR(80) NULL,
    fuente_datos VARCHAR(80) NULL,
    puntos_maximos NUMERIC(6, 2) NOT NULL,
    parametros_json VARCHAR(4000) NULL,
    adherencia7d_json VARCHAR(2000) NULL,
    fuente VARCHAR(1000) NULL,
    organismo_autor VARCHAR(255) NULL,
    version_anio VARCHAR(80) NULL,
    referencia VARCHAR(1000) NULL,
    tipo_fuente VARCHAR(40) NOT NULL
        CONSTRAINT chk_criterio_gt_fuente CHECK (tipo_fuente IN (
            'REFERENCIA_EXTERNA', 'REGLA_OPERACIONAL_PROPUESTA',
            'REGLA_OPERACIONAL_DEL_INSTRUMENTO', 'JUICIO_ESPECIALISTA')),
    orden INTEGER NOT NULL,
    activo BOOLEAN NOT NULL,
    CONSTRAINT uq_criterio_gt UNIQUE (rubrica_id, codigo)
);
CREATE INDEX idx_criterio_gt_dimension ON criterios_rubrica_perfil_habitos (dimension_id);

CREATE TABLE criterios_clasificacion_perfil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rubrica_id BIGINT NOT NULL REFERENCES rubricas_perfil_habitos (id),
    clasificacion VARCHAR(255) NOT NULL
        CONSTRAINT chk_clasif_perfil CHECK (clasificacion IN (
            'ADECUADO', 'MEJORABLE', 'CRITICO')),
    limite_inferior NUMERIC(6, 2) NOT NULL,
    limite_superior NUMERIC(6, 2) NOT NULL,
    incluye_inferior BOOLEAN NOT NULL,
    incluye_superior BOOLEAN NOT NULL,
    orden INTEGER NOT NULL,
    CONSTRAINT uq_clasif_perfil UNIQUE (rubrica_id, clasificacion),
    CONSTRAINT uq_clasif_perfil_orden UNIQUE (rubrica_id, orden)
);

CREATE TABLE evaluaciones_perfil_habitos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    rubrica_id BIGINT NOT NULL REFERENCES rubricas_perfil_habitos (id),
    evaluador_usuario_id BIGINT NOT NULL REFERENCES usuarios (id),
    fecha_evaluacion TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_corte DATE NOT NULL,
    puntaje_total NUMERIC(6, 2) NOT NULL,
    puntaje_maximo_calculable NUMERIC(6, 2) NULL,
    cobertura_calculable NUMERIC(6, 2) NULL,
    motivo_no_valida VARCHAR(1000) NULL,
    clasificacion_real VARCHAR(255) NOT NULL
        CONSTRAINT chk_eval_gt_clasif CHECK (clasificacion_real IN (
            'ADECUADO', 'MEJORABLE', 'CRITICO')),
    estado_validez VARCHAR(255) NOT NULL,
    observacion VARCHAR(2000) NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_eval_gt_cliente ON evaluaciones_perfil_habitos (cliente_id);

CREATE TABLE resultados_dimension_perfil_habitos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id BIGINT NOT NULL REFERENCES evaluaciones_perfil_habitos (id),
    dimension_id BIGINT NOT NULL REFERENCES dimensiones_rubrica_perfil_habitos (id),
    puntos_obtenidos NUMERIC(6, 2) NOT NULL,
    puntos_maximos_calculables NUMERIC(6, 2) NOT NULL,
    cobertura_calculable NUMERIC(6, 2) NOT NULL,
    criterios_no_calculables VARCHAR(2000) NULL,
    observacion VARCHAR(2000) NULL,
    CONSTRAINT uq_resultado_dimension UNIQUE (evaluacion_id, dimension_id)
);

CREATE TABLE resultados_criterio_perfil_habitos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id BIGINT NOT NULL REFERENCES evaluaciones_perfil_habitos (id),
    criterio_id BIGINT NOT NULL REFERENCES criterios_rubrica_perfil_habitos (id),
    estado VARCHAR(80) NOT NULL
        CONSTRAINT chk_resultado_criterio CHECK (estado IN (
            'CUMPLE', 'NO_CUMPLE', 'NO_CALCULABLE', 'MANUAL_PENDIENTE', 'DESCRIPTIVO',
            'SUPERA_UMBRAL_TOTAL_DESDE_SUPLEMENTOS',
            'SIN_EXCESO_DOCUMENTADO_SOLO_POR_SUPLEMENTOS')),
    valor_observado NUMERIC(12, 4) NULL,
    puntos_obtenidos NUMERIC(6, 2) NULL,
    puntos_maximos NUMERIC(6, 2) NULL,
    referencia_aplicada VARCHAR(1000) NULL,
    motivo_no_calculable VARCHAR(1000) NULL,
    observacion VARCHAR(2000) NULL,
    CONSTRAINT uq_resultado_criterio UNIQUE (evaluacion_id, criterio_id)
);

-- Planes nutricionales --------------------------------------------------------
CREATE TABLE planes_diarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    prediccion_modelo_origen_id BIGINT NULL REFERENCES predicciones_modelo (id),
    fecha_objetivo DATE NOT NULL,
    estado VARCHAR(255) NOT NULL
        CONSTRAINT chk_plan_estado CHECK (estado IN ('DISPONIBLE', 'NO_DISPONIBLE')),
    energia_min_kcal NUMERIC(19, 2) NULL,
    energia_max_kcal NUMERIC(19, 2) NULL,
    proteina_ming NUMERIC(19, 2) NULL,
    proteina_maxg NUMERIC(19, 2) NULL,
    carbohidratos_ming NUMERIC(19, 2) NULL,
    carbohidratos_maxg NUMERIC(19, 2) NULL,
    grasas_ming NUMERIC(19, 2) NULL,
    grasas_maxg NUMERIC(19, 2) NULL,
    motivo_no_disponible VARCHAR(1000) NULL,
    fuente_referencia VARCHAR(300) NULL,
    version_referencia VARCHAR(100) NULL,
    CONSTRAINT uq_plan_diario UNIQUE (cliente_id, fecha_objetivo)
);

CREATE TABLE cumplimientos_diarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_diario_id BIGINT NOT NULL UNIQUE REFERENCES planes_diarios (id),
    energia_estado VARCHAR(255) NULL
        CONSTRAINT chk_cumpl_energia CHECK (energia_estado IN (
            'CUMPLIDA', 'POR_DEBAJO', 'POR_ENCIMA', 'NO_CALCULABLE')),
    proteina_estado VARCHAR(255) NULL
        CONSTRAINT chk_cumpl_proteina CHECK (proteina_estado IN (
            'CUMPLIDA', 'POR_DEBAJO', 'POR_ENCIMA', 'NO_CALCULABLE')),
    carbohidratos_estado VARCHAR(255) NULL
        CONSTRAINT chk_cumpl_carbos CHECK (carbohidratos_estado IN (
            'CUMPLIDA', 'POR_DEBAJO', 'POR_ENCIMA', 'NO_CALCULABLE')),
    grasas_estado VARCHAR(255) NULL
        CONSTRAINT chk_cumpl_grasas CHECK (grasas_estado IN (
            'CUMPLIDA', 'POR_DEBAJO', 'POR_ENCIMA', 'NO_CALCULABLE')),
    energia_consumido NUMERIC(19, 2) NULL,
    energia_diferencia NUMERIC(19, 2) NULL,
    energia_porcentaje NUMERIC(19, 2) NULL,
    proteina_consumido NUMERIC(19, 2) NULL,
    proteina_diferencia NUMERIC(19, 2) NULL,
    proteina_porcentaje NUMERIC(19, 2) NULL,
    carbohidratos_consumido NUMERIC(19, 2) NULL,
    carbohidratos_diferencia NUMERIC(19, 2) NULL,
    carbohidratos_porcentaje NUMERIC(19, 2) NULL,
    grasas_consumido NUMERIC(19, 2) NULL,
    grasas_diferencia NUMERIC(19, 2) NULL,
    grasas_porcentaje NUMERIC(19, 2) NULL
);

CREATE TABLE intervenciones_consumo_diarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    evaluacion_consumo_id BIGINT NOT NULL REFERENCES evaluaciones_consumo (id),
    plan_diario_id BIGINT NULL REFERENCES planes_diarios (id),
    criterio_evaluado_id BIGINT NULL,
    componente VARCHAR(100) NULL,
    fuente_exceso VARCHAR(30) NULL,
    referencia_utilizada VARCHAR(1000) NULL,
    mensaje_estructurado VARCHAR(1000) NULL,
    CONSTRAINT uq_intervencion UNIQUE (evaluacion_consumo_id, criterio_evaluado_id)
);
