package com.backend.nutri_predic.indicador.dto;

public enum MotivoExclusionTpp {
    PROCEDIMIENTO_NO_APLICABLE,
    INICIO_AUSENTE,
    RESULTADO_AUSENTE,
    ORDEN_TEMPORAL_INVALIDO,
    EVENTO_INVALIDO,
    NO_DIARIO,
    VERSION_NO_V6,
    RESULTADO_REUTILIZADO,
    CICLO_INCOMPLETO,
    CICLO_FALLIDO,
    DURACION_CICLO_INVALIDA
}
